version: '3.9'

services:
  skm-server:
    build:
      context: sri-kula-medura-server
      dockerfile: Dockerfile
    ports: 
      - "8080:8080"
    networks:
      - skm
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://skmdb:3306/skm_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: abcd12@ABCD
    depends_on:
      - skmdb

  skmdb:
    image: mysql
    restart: always
    networks:
      - skm
    environment:
      MYSQL_DATABASE: skm_db
      MYSQL_USER: skm_user
      MYSQL_PASSWORD: abcd12@ABCD
      MYSQL_ROOT_PASSWORD: abcd12@ABCD
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - skm-db:/var/lib/mysql

networks:
  skm:
volumes:
  skm-db: